#(C) Copyright 2022, 2024 Hewlett Packard Enterprise Development LP

run:
  deadline: 240s

issues:
  exclude-dirs:
    - vendor
    - docs
    - build

linters-settings:
  goheader:
    template: '{{ copy }}'
    values:
      regexp: 
        range: (([0-9]{4}(,\s?|-))*{{ year }})
        copy: ^\(C\) Copyright {{ range }} Hewlett Packard Enterprise Development LP$
        
  exhaustive:
    default-signifies-exhaustive: true

  wsl:
    force-case-trailing-whitespace: 1

  dupl:
    threshold: 110

  lll:
    line-length: 128
    # tab width in spaces. Default to 1.
    tab-width: 1

  gci:
    # Group all projects under hewlettpackard together and separate from internal and 3rd party
    sections:
      - Standard
      - Default
      - 'prefix(github.com/hewlettpackard)'

  goimports:
    local-prefixes: github.com/hewlettpackard

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exportloopref
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - wrapcheck
    - wsl
    - whitespace
