#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

run:
  deadline: 240s
  skip-dirs:
    - vendor
    - docs
    - build

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  wsl:
    force-case-trailing-whitespace: 1

  dupl:
    threshold: 110

  lll:
    line-length: 128
    # tab width in spaces. Default to 1.
    tab-width: 1

issues:
  new-from-rev: origin/master

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exportloopref
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - wrapcheck
    - wsl
    - whitespace
