#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: ci

on: [push]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GO linter checks
        # Fetching origin/master for lint issue calculation before running checks
        run: |
          git fetch origin master  
          make tools  
          make lint

      - name: Build the code
        run: make build

      - name: Install locally
        run: make install

      - name: Verify document generation
        run: make docs
