#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: ci

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GO linters-settings
        run: make lint

      - name: Build the code
        run: make build
        continue-on-error: true

      - name: Install locally
        run: make install
        continue-on-error: true

      - name: Verify document generation
        run: make docs
