#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: ci

on: [push]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run GO linter checks
        # Fetching origin/master for lint issue calculation before running checks
        run: |
          make tools

          TARGET_BRANCH=${{ github.base_ref }}        
          if [[ ${TARGET_BRANCH} == "" ]]; then
            TARGET_BRANCH='master'
          fi
          echo "TARGET BRANCH is ${TARGET_BRANCH}"
