#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: ci

on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GO linter checks
        # Fetching origin/master for lint issue calculation before running checks
        run: |
          echo "Baseref is ${{ github.base_ref }} "
          make tools
          TARGET_BRANCH=${{ github.base_ref }}
          TARGET_SHA=`git merge-base -a HEAD origin/${TARGET_BRANCH}`
          echo Running lint on changes from branch ${TARGET_BRANCH} ${TARGET_SHA}
          golangci-lint version
          golangci-lint run --config golangci-lint-config.yaml --new-from-rev ${TARGET_SHA} --timeout 600s --verbose --max-issues-per-linter 0 --max-same-issues 0
